# =========================================================
# BUILD STAGE
# Spring Boot 3.5.6 + Java 21
# =========================================================

FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests


# =========================================================
# RUNTIME STAGE
# Java 21
# =========================================================

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/target/sih26132-backend-0.0.1-SNAPSHOT.jar app.jar

ENV PORT=80

CMD ["sh", "-c", "java -Dserver.port=${PORT} -jar app.jar"]