spring.datasource.url=jdbc:postgresql://localhost:5432/sih26132_db
spring.datasource.username=postgres
spring.datasource.password=123a

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# =========================================================
# JWT Configuration
# =========================================================

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

app.file-storage.location=uploads

# =========================================================
# OpenAI Embedding Configuration
# =========================================================

openai.api-key=${OPENAI_API_KEY}
openai.embedding-url=https://api.openai.com/v1/embeddings
openai.embedding-model=text-embedding-3-small

# =========================================================
# OpenAI LLM Configuration
# =========================================================

openai.chat-url=https://api.openai.com/v1/responses
openai.chat-model=gpt-5-mini

logging.level.org.springframework.security=DEBUG
ml.service.url=http://127.0.0.1:8000